arr = []

n = int(input())

arr = input().split()

for i in range(n):
    if arr[i] == '.-': print("A", end='')
    elif arr[i] == '-...': print("B", end='')
    elif arr[i] == '-.-.': print("C", end='')
    elif arr[i] == '-..': print("D", end='')
    elif arr[i] == '.': print("E", end='')
    elif arr[i] == '..-.': print("F", end='')
    elif arr[i] == '--.': print("G", end='')
    elif arr[i] == '....': print("H", end='')
    elif arr[i] == '..': print("I", end='')
    elif arr[i] == '.---': print("J", end='')
    elif arr[i] == '-.-': print("K", end='')
    elif arr[i] == '.-..': print("L", end='')
    elif arr[i] == '--': print("M", end='')
    elif arr[i] == '-.': print("N", end='')
    elif arr[i] == '---': print("O", end='')
    elif arr[i] == '.--.': print("P", end='')
    elif arr[i] == '--.-': print("Q", end='')
    elif arr[i] == '.-.': print("R", end='')
    elif arr[i] == '...': print("S", end='')
    elif arr[i] == '-': print("T", end='')
    elif arr[i] == '..-': print("U", end='')
    elif arr[i] == '...-': print("V", end='')
    elif arr[i] == '.--': print("W", end='')
    elif arr[i] == '-..-': print("X", end='')
    elif arr[i] == '-.--': print("Y", end='')
    elif arr[i] == '--..': print("Z", end='')
    elif arr[i] == '-----': print("0", end='')
    elif arr[i] == '.----': print("1", end='')
    elif arr[i] == '..---': print("2", end='')
    elif arr[i] == '...--': print("3", end='')
    elif arr[i] == '....-': print("4", end='')
    elif arr[i] == '.....': print("5", end='')
    elif arr[i] == '-....': print("6", end='')
    elif arr[i] == '--...': print("7", end='')
    elif arr[i] == '---..': print("8", end='')
    elif arr[i] == '----.': print("9", end='')
    elif arr[i] == '--..--': print(",", end='')
    elif arr[i] == '.-.-.-': print(".", end='')
    elif arr[i] == '..--..': print("?", end='')
    elif arr[i] == '---...': print(":", end='')
    elif arr[i] == '-....-': print("-", end='')
    elif arr[i] == '.--.-.': print("@", end='')